spring.profiles.default=dev

server.port=8080

spring.jpa.open-in-view=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.thymeleaf.cache=false

app.name=SmartStock AI
app.low-stock-threshold=5

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
