ALTER TABLE sale_transaction
    ADD COLUMN IF NOT EXISTS voided BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS voided_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS voided_by VARCHAR(255),
    ADD COLUMN IF NOT EXISTS void_reason VARCHAR(255);
